---
- name: Copy Cisco Image from TFTP
  hosts: switch_uaca
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Copy image from TFTP server
      cli_command:
        command: "copy tftp://10.11.104.237/cat9k_lite_iosxe.17.06.05.SPA.bin flash:cat9k_lite_iosxe.17.06.05.SPA.bin"
        prompt:
          - "Destination filename"
        answer:
          - "Destination filename"

    - name: Print copy output
      debug:
        var: copy_output
